### ISSUE TITLE
Display in 15" old laptop

### ISSUE THREAD

**Issue by fgurrea** [vrybant/unboundbible#1]
Hello Vladimir, could it be possible to fix an error when using VBD in old laptops with 15 inches screeen, not the current 15.4 flat panel. My screen is from an old Dell Latitude D520 and the resolution is XGA 1024x768, this is the maximum I can get. The problem could be due that the screen aspect ratio in XGA is 4:3  different from modern screens with 15.4 inches and 16:10 aspect ratio.

Please find the attached image 

![bvd-15screen](https://cloud.githubusercontent.com/assets/18749924/14936821/31124030-0ef6-11e6-9464-510f8e44c0b8.jpg)

**Comment by vrybant** [comment]
Hello Francisco, what is your operation sistem?

**Comment by fgurrea** [comment]
Hello, and apologies for not saying before, it is Windows 7…quite important detail of course

Thank you for your quick reply

Francisco

De: Vladimir Rybant [mailto:notifications@github.com] 
Enviado el: domingo, 01 de mayo de 2016 18:11
Para: vrybant/Unbound-Bible-Tools
CC: fgurrea; Author
Asunto: Re: [vrybant/Unbound-Bible-Tools] Display in 15" old laptop (#1)

Hello Francisco, what is your operation sistem?

**Comment by vrybant** [comment]
Do you have latest 4.0 version of Bible Verse Desktop?

**Comment by fgurrea** [comment]
Yes, I have the latest 4.0.
Perhaps the problem could be related to the laptop video card ?
Sorry, I don't want to disturb you, perhaps you don't have much time
to work on this

Thanks

2016-05-02 7:05 GMT+02:00, Vladimir Rybant notifications@github.com:

**Comment by vrybant** [comment]
You do not disturb me at all. Bug reports are very important. Thank you for you message! But I need a time to investigate this problem.
