### ISSUE TITLE
Aplicativo de Bíblia maravilhoso!

### ISSUE THREAD

**Issue by FlavioTheoLima** [vrybant/unboundbible#10]
Olá!
Estou escrevendo para parabenizar a todos os envolvidos no projeto. Instalei o aplicativo é achei ele fantástico!
Gostaria de saber se há possibilidade de tradução dos nomes dos livros?
Sou do Brasil.

**Comment by vrybant** [comment]
Hi! 
Bibles names embedded in modules. You should try different ones.

**Comment by FlavioTheoLima** [comment]
Hello!!
In other languages it changes normally, but in Brazilian Portuguese the
names of the books in the letter remain in English.

Em sáb., 25 de fev. de 2023 às 07:45, Vladimir Rybant <
***@***.***> escreveu:
