### ISSUE TITLE
Create a Portable version

### ISSUE THREAD

**Issue by pepaulo** [vrybant/unboundbible#11]
The Unbound Bible is a fantastic app. There are the possibity of one Windows Portable Version? Is possible to change the default modules directory? God bless you!

**Comment by rchastain** [comment]
Hello! I use daily UnboundBible under Windows, on a USB key. My bibles are in `<UnboundBibleDirectory>/bibles/`, and it works well. So, I would say that UB is already portable.

**Comment by pepaulo** [comment]
> Hello! I use daily UnboundBible under Windows, on a USB key. My bibles are in `<UnboundBibleDirectory>/bibles/`, and it works well. So, I would say that UB is already portable.

Thank you for the answer. God bless you. I Will make a Portable Apps version If It is  possible.

**Comment by rchastain** [comment]
> God bless you.

Amen!

> I Will make a Portable Apps version If It is possible.

I think we just need to put the executable in a ZIP file or in a self-extracting archive. (I don't think that the Portable Apps system be really useful in that case).

I will take a look ASAP. (For me I use Linux.)

**Comment by rchastain** [comment]
Finally I made a portable version of Unbound Bible. I hope that Vladimir doesn't mind.

You can find a package for Windows 32-bit [here](https://sourceforge.net/projects/unbound-bible-portable/files/5.4/). I will upload a Linux version later.

The modification that I made in source code is very simple.

```pascal
// unitutils.pas

function DataPath: string;
begin
  (*
  Result := GetUserDir + ApplicationName;
  *)
  Result := ExtractFilePath(ParamStr(0)) + 'data';
end;

(* ... *)

function ConfigPath: string;
begin
  (*
  {$ifdef windows} Result := LocalAppDataPath + ApplicationName;  {$endif}
  {$ifdef unix}    Result := GetUserDir + '.config/unboundbible'; {$endif}
  *)
  Result := ExtractFilePath(ParamStr(0)) + 'config';
```

@pepaulo 
Please let me know if this is what you needed.

Best regards.

Roland

**Comment by vrybant** [comment]
Hi! I added portable directive to code.

{$define portable}   

[https://github.com/vrybant/unboundbible/commit/bc70ae49a2d75a5f9242a05619fe27361c104ecc](https://github.com/vrybant/unboundbible/commit/bc70ae49a2d75a5f9242a05619fe27361c104ecc)

**Comment by rchastain** [comment]
Good! So I think I can delete the Sourceforge page that I had created.
