### ISSUE TITLE
Switch Localization to Lazarus builtin i18n

### ISSUE THREAD

**Issue by reckel-jm** [vrybant/unboundbible#14]
Lazarus has a built-in i18n localization support and is able to automatically create *.po files which can then be translated and compiled to *.mo files. This allows the program to automatically adapt to the systems language and also provides a standardized way of doing translation (you can use an external program like poedit as well). See more details in the wiki: https://wiki.freepascal.org/Translations_/_i18n_/_localizations_for_programs
I recommend switching to Lazarus built-in i18n.

God bless you!

**Comment by vrybant** [comment]
Is it possible to swich languages by this way without restarting program?

**Comment by reckel-jm** [comment]
Yes that should be possible but I haven't testet it so far. Check out https://wiki.freepascal.org/Step-by-step_instructions_for_creating_multi-language_applications#Format_settings and https://wiki.freepascal.org/Translations_/_i18n_/_localizations_for_programs for details.

**Comment by vrybant** [comment]
Ok. I'll think about it.
