### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by rchastain** [vrybant/unboundbible#15]
Hello!

I have just compiled on Linux Unbound Bible 5.4 and when I run it I get this error:

```
[roland@localhost unboundbible-5.4]$ ./unboundbible_linux 
connection failed /home/roland/Unbound Bible/BdM.SQLite3
connection failed /home/roland/Unbound Bible/CVg.SQLite3
connection failed /home/roland/Unbound Bible/BCC'1923.SQLite3
connection failed /home/roland/Unbound Bible/VulgateClementine.bbl.mybible
connection failed /home/roland/Unbound Bible/MENG.SQLite3
connection failed /home/roland/Unbound Bible/SCH'51.SQLite3
connection failed /home/roland/Unbound Bible/Grun.SQLite3
connection failed /home/roland/Unbound Bible/gerlut.bbl.mybible
connection failed /home/roland/Unbound Bible/PAT80.SQLite3
connection failed /home/roland/Unbound Bible/kjv.bbl.unbound
connection failed /home/roland/Unbound Bible/frecrampon.bbl.mybible
connection failed /home/roland/Unbound Bible/KJV1611.SQLite3
connection failed /home/roland/Unbound Bible/gerlut1545.bbl.mybible
connection failed /home/roland/Unbound Bible/strong.dct.unbound
connection failed /home/roland/Unbound Bible/ob.xrefs.unbound
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000469929
  $0000000000466FF3
  $0000000000466F7D
  $0000000000469C62
  $0000000000425B1C
Exception at 0000000000469929: EAccessViolation:
Access violation.
[roland@localhost unboundbible-5.4]$ 
```

For information, I downloaded ZeosDBO from svn, as indicated in _README.md_.

The weird thing is that I have, on the same computer, another binary of the same version, that I had compiled some weeks ago, and it works well. I don't remember which version of ZeosDBO I used when I compiled that binary.

What could be the explanation for the "connection failed" error?

Best regards.

Roland

**Comment by reckel-jm** [comment]
That seems like a Lazarus linking error for me. Which version of Lazarus do you use and which versions do the libraries have? Especially when using older Ubuntu versions, it might be helpful to update to the newest Lazarus versions.

BTW: I am thinking of adding a snap package of Lazarus which would make the usage of unboundbible on Linux much easier. When I have time I will create a pull request for that as soon as possible.

**Comment by rchastain** [comment]
Thank you for your answer. I use Lazarus 2.2.4. For the libraries, I don't know.

**Comment by reckel-jm** [comment]
That is indeed the newest version. Which Linux distribution and architecture are you using? Did you run the steps as described in the [Readme](https://github.com/vrybant/unboundbible#build-instructions) file?

**Comment by rchastain** [comment]
It's Linux Mageia 64. Yes, I followed the steps.

I don't know if this is related, but I tried to install ZComponent from the latest stable version of ZeosDBO (7.2.14), to see if it would solve the issue. Lazarus says that it cannot be installed because some packages are missing: **fcl-db** and **fcl-process**.

**Comment by vrybant** [comment]
I think you need to install libsqlite3.so lib.

sudo aptitude install sqlite3

Copy @libsqlite3.so.0 and libsqlite3.so.0.8.6 from /usr/lib/x86_64-linux-gnu to /usr/lib
Rename @libsqlite3.so.0 to @libsqlite3.so

**Comment by rchastain** [comment]
@vrybant 

Thank you for your answer.

I already have SQLite installed:

```
[roland@localhost 06]$ locate libsqlite3
/usr/lib64/libsqlite3.so
/usr/lib64/libsqlite3.so.0
/usr/lib64/libsqlite3.so.0.8.6
```

And, as I said, I have a binary of UnboundBible (the same version) that I compiled some time ago, which works well.

By the way, I am on Linux Mageia, where **aptitude** doesn't exist.

**Comment by vrybant** [comment]
@rchastain 

I installed  Linux Mageia in VirtualBox and tested. It works!

For lazarus you need to have libsqlite3.so file in /usr/lib dirictory not only in /usr/lib64.
Copy @libsqlite3.so.0 and libsqlite3.so.0.8.6 to /usr/lib and rename @libsqlite3.so.0 to @libsqlite3.so
