### ISSUE TITLE
How to include bibles in other languages

### ISSUE THREAD

**Issue by rchastain** [vrybant/unboundbible#2]
Hello! Congratulations for your nice project. I could compile it without any problem under Linux 64.
How could I use bibles in other languages?
Best regards.
Roland

**Comment by vrybant** [comment]
Hi Roland! Thank you for your message. You can use bibles in many languages. 
Read this [manual](http://vladimirrybant.org/index.php?page=download)

**Comment by rchastain** [comment]
Great! Thank you.

**Comment by rchastain** [comment]
Hi @vrybant!

The link to the manual is broken now. Please could you include a manual in this repository? Or at less provide a link to websites where we can download modules.

**Comment by vrybant** [comment]
> Hi [@vrybant](https://github.com/vrybant)!
> 
> The link to the manual is broken now. Please could you include a manual in this repository? Or at less provide a link to websites where we can download modules.

[https://unboundbible.net/index.php?page=download](https://unboundbible.net/index.php?page=download)

**Comment by rchastain2** [comment]
Thank you.
