### ISSUE TITLE
Source code of release 5.1 cannot be compiled

### ISSUE THREAD

**Issue by rchastain** [vrybant/unboundbible#3]
Hello! Congratulations for the new release.

There seems to be a problem with the source code of the release: I cannot compile it.

Fortunately, no problem with the *.rpm package.

Regards.

Roland

**Comment by JulStrat** [comment]
1. Install components.
2. Apply patch 

$ git diff unitbible.pas
diff --git a/unitbible.pas b/unitbible.pas
index 1405406..e98e146 100644
--- a/unitbible.pas
+++ b/unitbible.pas
@@ -406,7 +406,7 @@ end;

 function TBible.Search(searchString: string; SearchOptions: TSearchOptions; Range: TRange): TContentArray;
 var
-  Contents : TContentArray = [];
+  Contents : TContentArray; // = [];
   queryRange : string = '';
   from, till : string;
   nt : boolean;

$ git diff unitlib.pas
diff --git a/unitlib.pas b/unitlib.pas
index 12c36ea..2f21aac 100644
--- a/unitlib.pas
+++ b/unitlib.pas
@@ -124,7 +124,7 @@ end;

 function StringToList(ch: Char; s: string): TStringArray;
 var
-  Point : array of integer = [];
+  Point : array of integer; // = [];
   index : integer = 0;
   n : integer = 0;
   i, len : integer;

Regards.

**Comment by rchastain** [comment]
@JulStrat 

Thank you. With the modifications that you suggested it compiles.
I could also compile it without modifications, on another computer where I have FPC 3.2.0. I should have understood that the problem came from that. :)

**Comment by JulStrat** [comment]
I compiled on Lazarus 2.0.6/FPC 3.0.4/Windows Vista 32bit. I think it's compiler ...

**Comment by rchastain** [comment]
> I compiled on Lazarus 2.0.6/FPC 3.0.4/Windows Vista 32bit. I think it's compiler ...

Yes. And for me I had also another problem, because I was using the packages from the previous version. When I recompiled the package, the error disappeared.

Thank you for your help!

**Comment by JulStrat** [comment]
> 
> 
> > I compiled on Lazarus 2.0.6/FPC 3.0.4/Windows Vista 32bit. I think it's compiler ...
> 
> Yes. And for me I had also another problem, because I was using the packages from the previous version. When I recompiled the package, the error disappeared.
> 
> Thank you for your help!

My pleasure.
Regards.
