### ISSUE TITLE
Feature suggestion: a button to uninstall bibles

### ISSUE THREAD

**Issue by rchastain** [vrybant/unboundbible#4]
Hello Vladimir!

Congratulations for the new release of your beautiful software.

In the modules window, maybe you could add a button to uninstall a selected module? Each time I install a new version, I get modules that I don't need and I waste time to delete them manually.

By the way, there are two or three things not translated in french (for example the menu item "donate"). I can translate them if you want (and if you provide me the file that I have to edit).

Regards.

Roland

**Comment by vrybant** [comment]
Hello @rchastain !

Thank you for feedback! Yes, I am going to make remove button soon. 
Concerning french translation you need to fix this file -  https://github.com/vrybant/unboundbible/blob/master/localization/french.lng

Blessings

**Comment by rchastain** [comment]
> Concerning french translation you need to fix this file - https://github.com/vrybant/unboundbible/blob/master/localization/french.lng
> 
Thank you for your answer. Here is the file updated. (I used the file from the v5.3 release package. I hope it's OK.)

(By the way, in the english version, I believe that the text should be "verses were found" instead of "verses was found". There are several verses, isn't it?)

Regards.

Roland
[french.lng.zip](https://github.com/vrybant/unboundbible/files/6252288/french.lng.zip)

**Comment by vrybant** [comment]
Thank you! I updated it. 

> (By the way, in the english version, I believe that the text should be "verses were found" instead of "verses was found". There are several verses, isn't it?)

Oops.. You are rigth!

**Comment by rchastain** [comment]
> Thank you! I updated it.
> 
You are welcome. I didn't change many things. Just translated "donate" and retouched two or three other things.

**Comment by rchastain** [comment]
Sorry, I see I made a typo. Please find here the new file.
[french.lng.zip](https://github.com/vrybant/unboundbible/files/6252427/french.lng.zip)

**Comment by rchastain** [comment]
Hello Vladimir!

I see that it is possible to select bibles, by clicking on the first button of the toolbar. (I had never tried before.) So it is not necessary to add another button.

But the hint ('Bible') isn't very understandable. Why not 'Select my favourite bibles', or something like that?

![screenshot1](https://user-images.githubusercontent.com/13957204/113504875-7ac0d900-953b-11eb-80b8-b8b8709d0862.png)
![screenshot2](https://user-images.githubusercontent.com/13957204/113504877-7bf20600-953b-11eb-837a-4cff0872e3c4.png)

**Comment by vrybant** [comment]
Hi Roland!
I made this feature  in last version but I am goin to remove it and make delete buttom.

**Comment by rchastain** [comment]
Hi Vladimir!
OK, as you prefer.
Bye!

**Comment by vrybant** [comment]
Hi Roland! Translate please to french this sentence: "Do you wish to delete this module?"

**Comment by rchastain** [comment]
> Hi Roland! Translate please to french this sentence: "Do you wish to delete this module?"

Hi Vladimir!

"Souhaitez-vous supprimer ce module ?"

**Comment by vrybant** [comment]
Thanks!
