### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by B-Interactive** [vrybant/unboundbible#8]
This is a request more than an issue.  I was wondering if you could add build instructions to [README.md](https://github.com/vrybant/unboundbible/blob/master/README.md) please.

**Comment by yochananmarqos** [comment]
Something like this I think, but it eventually runs into an error building and complains the Lazarus directory is read-only. 

```
lazbuild -B --lazarusdir=/usr/lib/lazarus --build-ide= --add-package components/zeosdbo/packages/lazarus/zcomponent.lpk
```
