### ISSUE TITLE
Do you know the Crosswire projet?

### ISSUE THREAD

**Issue by LAfricain** [vrybant/unboundbible#9]
Hi @vrybant this is not exactly an issue. But more to get in touch. Do you know the [Crosswire project](http://crosswire.org/)? And the software coming with: [xiphos](https://xiphos.org/) and [bibletime](http://bibletime.info/) for PC and mac?
I'm just interesting you about an other biblical software.

**Comment by vrybant** [comment]
Hi! Yes, I am familiar with these projects. Why are you asking?

**Comment by LAfricain** [comment]
I ask because I see that Unbound seems abandoned. (Almost the bible module are no more available). But mostly because I realize that there is a lot of biblical software out there, and I'd like the idea of federating it all. At least as far as modules are concerned. Moreover the Crosswire developers are not very numerous and I hope to be able to motivate new people who would be interested by a software that could gather most of the features of the biblical software. But Xiphos and Bibletime seem to me the most advanced in Opensource.

**Comment by vrybant** [comment]
Unbound is not abandoned ;) And this is crossplatform Open Sourse software with native (!) interfaces. iOS and Android platforms are coming soon. Concerning modules, there are many [modules](https://unboundbible.net/index.php?page=download) in mybible and mysword formats that we can use.

**Comment by LAfricain** [comment]
> Unbound is not abandoned ;) 

Good to know! How to you manage the copyright of your module, and how do you manage the issues? We have a tracker: https://tracker.crosswire.org/projects/MOD/issues/MOD-290?filter=allopenissues

**Comment by vrybant** [comment]
I do not make modules, but only software.

**Comment by LAfricain** [comment]
OK, and who makes it?

**Comment by vrybant** [comment]
[www.ph4.org](https://www.ph4.org/b4_1all.php)

**Comment by LAfricain** [comment]
Thank you.
